# Generated by Django 5.2 on 2025-04-22 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refrendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20)),
                ('numero_refrendo', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('tipo', models.CharField(choices=[('TITULO', 'De Título'), ('CURSO', 'De Curso')], max_length=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='refrendos/pdf/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='refrendos/img/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refrendos.curso')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refrendos.titulo')),
            ],
        ),
    ]
