# Generated by Django 5.2 on 2025-04-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refrendos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refrendo',
            options={'permissions': [('ver_refrendo', 'Puede ver refrendos'), ('crear_refrendo', 'Puede crear refrendos'), ('editar_refrendo', 'Puede editar refrendos'), ('borrar_refrendo', 'Puede borrar refrendos')]},
        ),
    ]
