# Generated by Django 5.2 on 2025-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrendos', '0002_alter_refrendo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrendo',
            name='dias_corridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refrendo',
            name='dias_habiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refrendo',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
